[general]
theme = "github-dark"
cache = "./cache"
log_level = "INFO"
username = "Reaven010"
debug = false

[refresh]
github = 600
leetcode = 900
weather = 900
media = 2
git = 5
system = 1

[github]
enabled = true
username = "Reaven010"
access_token = ""

[leetcode]
enabled = true
username = ""

[weather]
enabled = false
api_key = ""
city = ""
units = "metric"      # metric | imperial

[music]
enabled = true
player = "auto"       # auto | spotify | vlc | mpv

[system]
cpu = true
memory = true
disk = true
network = true
temperature = true
battery = true